import { MasterType } from '../src/modules/config/master.model';

export interface MasterSeedRow {
  masterType: MasterType;
  key: string;
  label: string;
  sortOrder?: number;
  meta?: Record<string, unknown>;
}

function rows(masterType: MasterType, items: [string, string, Record<string, unknown>?][]): MasterSeedRow[] {
  return items.map(([key, label, meta], i) => ({ masterType, key, label, sortOrder: i, ...(meta ? { meta } : {}) }));
}
export const MASTER_SEED_DATA: MasterSeedRow[] = [
  ...rows('SERVICE_CATEGORY', [
    ['AC_REPAIR_SERVICE', 'AC Repair & Service'],
    ['APPLIANCE_REPAIR', 'Appliance Repair'],
    ['WATER_PURIFIER', 'Water Purifier Repair & Service'],
    ['CHIMNEY_KITCHEN', 'Chimney & Kitchen Appliance Repair'],
    ['GEYSER_REPAIR', 'Geyser Repair & Installation'],
    ['ELECTRICIAN', 'Electrician'],
    ['PLUMBER', 'Plumber'],
    ['CARPENTER', 'Carpenter'],
    ['PAINTING_WATERPROOFING', 'Painting & Waterproofing'],
    ['PEST_CONTROL', 'Pest Control'],
    ['HOME_DEEP_CLEANING', 'Home Deep Cleaning'],
    ['SOFA_CARPET_CLEANING', 'Sofa & Carpet Cleaning'],
    ['BATHROOM_KITCHEN_CLEANING', 'Bathroom & Kitchen Cleaning'],
    ['SALON_FOR_WOMEN', 'Salon for Women'],
    ['SALON_FOR_MEN', 'Salon for Men'],
    ['SPA_MASSAGE', 'Spa & Massage'],
    ['CCTV_SECURITY', 'CCTV & Home Security Installation'],
    ['WALL_PANELS', 'Wall Panels & False Ceiling'],
    ['PACKERS_MOVERS', 'Packers & Movers'],
    ['VEHICLE_CARE', 'Car & Bike Cleaning'],
  ]),

  ...rows('BRAND', [
    ['LG', 'LG'],
    ['SAMSUNG', 'Samsung'],
    ['VOLTAS', 'Voltas'],
    ['DAIKIN', 'Daikin'],
    ['BLUE_STAR', 'Blue Star'],
    ['WHIRLPOOL', 'Whirlpool'],
    ['GODREJ', 'Godrej'],
    ['HAIER', 'Haier'],
    ['PANASONIC', 'Panasonic'],
    ['IFB', 'IFB'],
    ['BOSCH', 'Bosch'],
    ['HITACHI', 'Hitachi'],
    ['CARRIER', 'Carrier'],
    ['O_GENERAL', 'O General'],
    ['LLOYD', 'Lloyd'],
    ['BAJAJ', 'Bajaj'],
    ['HAVELLS', 'Havells'],
    ['CROMPTON', 'Crompton'],
    ['SYMPHONY', 'Symphony'],
    ['LIVPURE', 'Livpure'],
    ['KENT', 'Kent'],
    ['EUREKA_FORBES', 'Eureka Forbes'],
    ['AO_SMITH', 'AO Smith'],
    ['V_GUARD', 'V-Guard'],
    ['ONIDA', 'Onida'],
  ]),

  ...rows('PRODUCT_TYPE', [
    ['SPLIT_AC', 'Split AC'],
    ['WINDOW_AC', 'Window AC'],
    ['REFRIGERATOR', 'Refrigerator'],
    ['WASHING_MACHINE', 'Washing Machine'],
    ['MICROWAVE_OVEN', 'Microwave Oven'],
    ['WATER_PURIFIER', 'Water Purifier'],
    ['CHIMNEY', 'Chimney'],
    ['GEYSER', 'Geyser / Water Heater'],
    ['TELEVISION', 'Television'],
    ['AIR_COOLER', 'Air Cooler'],
    ['DISHWASHER', 'Dishwasher'],
    ['AIR_PURIFIER', 'Air Purifier'],
    ['CEILING_FAN', 'Ceiling Fan'],
    ['INVERTER_STABILIZER', 'Inverter / Stabilizer'],
  ]),

  ...rows('SYMPTOM', [
    ['NOT_COOLING', 'Not Cooling'],
    ['NOT_HEATING', 'Not Heating'],
    ['WATER_LEAKAGE', 'Water Leakage'],
    ['GAS_LEAKAGE', 'Gas Leakage'],
    ['NOISE_FROM_UNIT', 'Unusual Noise'],
    ['FOUL_SMELL', 'Foul Smell'],
    ['REMOTE_NOT_WORKING', 'Remote Not Working'],
    ['NOT_TURNING_ON', 'Not Turning On'],
    ['FREQUENT_TRIPPING', 'Frequent Tripping / Power Cut'],
    ['ICE_FORMATION', 'Ice Formation'],
    ['LOW_AIRFLOW', 'Low Airflow'],
    ['NOT_SPINNING', 'Not Spinning'],
    ['NOT_DRAINING', 'Water Not Draining'],
    ['EXCESS_VIBRATION', 'Excessive Vibration'],
    ['DOOR_NOT_LOCKING', 'Door Not Locking / Sealing'],
    ['ERROR_CODE_DISPLAY', 'Error Code on Display'],
    ['SPARKING', 'Sparking'],
    ['SWITCH_NOT_WORKING', 'Switch / Socket Not Working'],
    ['LIGHT_FLICKERING', 'Light Flickering'],
    ['CLOGGED_DRAIN', 'Clogged Drain'],
    ['LOW_WATER_PRESSURE', 'Low Water Pressure'],
    ['TAP_LEAKING', 'Tap Leaking'],
    ['SLOW_COOLING', 'Slow / Insufficient Cooling'],
    ['DISPLAY_NOT_WORKING', 'Display Not Working'],
  ]),

  ...rows('DEFECT', [
    ['GAS_LEAKAGE', 'Gas Leakage'],
    ['COMPRESSOR_FAILURE', 'Compressor Failure'],
    ['PCB_FAULT', 'PCB Fault'],
    ['MOTOR_BURNT', 'Motor Burnt'],
    ['CAPACITOR_FAULTY', 'Capacitor Faulty'],
    ['THERMOSTAT_FAULTY', 'Thermostat Faulty'],
    ['FAN_MOTOR_FAILURE', 'Fan Motor Failure'],
    ['FILTER_CLOGGED', 'Filter Clogged'],
    ['DRAIN_PUMP_FAULTY', 'Drain Pump Faulty'],
    ['BELT_WORN_OUT', 'Belt Worn Out'],
    ['DOOR_SEAL_DAMAGED', 'Door Seal / Gasket Damaged'],
    ['WIRING_SHORT_CIRCUIT', 'Wiring Short Circuit'],
    ['SENSOR_MALFUNCTION', 'Sensor Malfunction'],
    ['BEARING_WORN_OUT', 'Bearing Worn Out'],
    ['VALVE_STUCK', 'Valve Stuck'],
    ['HEATING_ELEMENT_FAULTY', 'Heating Element Faulty'],
    ['WATER_INLET_VALVE_FAULTY', 'Water Inlet Valve Faulty'],
    ['CONTROL_PANEL_DAMAGE', 'Control Panel Damage'],
    ['RUST_CORROSION', 'Rust / Corrosion'],
    ['LOOSE_CONNECTION', 'Loose Connection'],
    ['CHOKED_PIPE', 'Choked Pipe'],
  ]),

  ...rows('SOLUTION', [
    ['GAS_REFILLING', 'Gas Refilling'],
    ['PART_REPLACEMENT', 'Part Replacement'],
    ['PCB_REPAIR', 'PCB Repair'],
    ['FULL_SERVICING', 'Full Servicing'],
    ['GENERAL_CLEANING', 'General Cleaning'],
    ['MOTOR_REPLACEMENT', 'Motor Replacement'],
    ['CAPACITOR_REPLACEMENT', 'Capacitor Replacement'],
    ['THERMOSTAT_REPLACEMENT', 'Thermostat Replacement'],
    ['FILTER_CLEANING_REPLACEMENT', 'Filter Cleaning / Replacement'],
    ['BELT_REPLACEMENT', 'Belt Replacement'],
    ['DOOR_SEAL_REPLACEMENT', 'Door Seal Replacement'],
    ['REWIRING', 'Rewiring'],
    ['SENSOR_REPLACEMENT', 'Sensor Replacement'],
    ['BEARING_REPLACEMENT', 'Bearing Replacement'],
    ['VALVE_REPLACEMENT', 'Valve Replacement'],
    ['HEATING_ELEMENT_REPLACEMENT', 'Heating Element Replacement'],
    ['DEEP_CLEANING', 'Deep Cleaning'],
    ['NEW_INSTALLATION', 'New Installation'],
    ['UNINSTALLATION', 'Uninstallation'],
    ['RELOCATION_SHIFTING', 'Relocation / Shifting'],
    ['NO_REPAIR_DEAD_UNIT', 'No Repair Possible (Dead Unit)'],
    ['WARRANTY_REFERRAL', 'Under Warranty — Manufacturer Referral'],
  ]),

  ...rows('PART', [
    ['COMPRESSOR', 'Compressor'],
    ['CONDENSER_COIL', 'Condenser Coil'],
    ['EVAPORATOR_COIL', 'Evaporator Coil'],
    ['REFRIGERANT_GAS', 'Refrigerant Gas (R32/R410A/R22)'],
    ['CAPACITOR', 'Capacitor'],
    ['PCB_BOARD', 'PCB Board'],
    ['REMOTE_CONTROL', 'Remote Control'],
    ['THERMOSTAT', 'Thermostat'],
    ['DRAIN_PUMP', 'Drain Pump'],
    ['MOTOR', 'Motor'],
    ['BELT', 'Belt'],
    ['DOOR_SEAL_GASKET', 'Door Seal / Gasket'],
    ['WATER_INLET_VALVE', 'Water Inlet Valve'],
    ['HEATING_ELEMENT', 'Heating Element'],
    ['FAN_BLADE', 'Fan Blade'],
    ['AIR_FILTER', 'Air Filter'],
    ['FUSE', 'Fuse'],
    ['RELAY', 'Relay'],
    ['SENSOR', 'Sensor'],
    ['BEARING', 'Bearing'],
    ['CONTROL_PANEL', 'Control Panel'],
    ['POWER_CORD', 'Power Cord'],
    ['TIMER', 'Timer'],
    ['DRUM', 'Drum'],
    ['WIRING_HARNESS', 'Wiring Harness'],
  ]),

  ...rows('UNIT', [
    ['PIECE', 'Piece'],
    ['HOUR', 'Hour'],
    ['KG', 'Kg'],
    ['LITRE', 'Litre'],
    ['METRE', 'Metre'],
    ['SQFT', 'Sq. Ft.'],
    ['SET', 'Set'],
    ['VISIT', 'Visit'],
    ['BOX', 'Box'],
    ['ROLL', 'Roll'],
  ]),

  ...rows('TAX_RATE', [
    ['GST_0', 'GST 0%', { rate: 0 }],
    ['GST_5', 'GST 5%', { rate: 5 }],
    ['GST_12', 'GST 12%', { rate: 12 }],
    ['GST_18', 'GST 18%', { rate: 18 }],
    ['GST_28', 'GST 28%', { rate: 28 }],
  ]),

  ...rows('PRIORITY', [
    ['LOW', 'Low'],
    ['NORMAL', 'Normal'],
    ['HIGH', 'High'],
    ['URGENT', 'Urgent'],
  ]),

  ...rows('LEAD_SOURCE', [
    ['WEBSITE', 'Website'],
    ['MOBILE_APP', 'Mobile App'],
    ['PHONE_CALL', 'Phone Call'],
    ['WALK_IN', 'Walk-in'],
    ['REFERRAL', 'Referral'],
    ['FACEBOOK_ADS', 'Facebook Ads'],
    ['GOOGLE_ADS', 'Google Ads'],
    ['INSTAGRAM', 'Instagram'],
    ['WHATSAPP', 'WhatsApp'],
    ['GOOGLE_MY_BUSINESS', 'Google My Business'],
    ['JUSTDIAL', 'Justdial'],
    ['INDIAMART', 'IndiaMART'],
    ['EXISTING_CUSTOMER', 'Existing Customer'],
    ['COLD_CALL', 'Cold Call'],
    ['FIELD_MARKETING', 'Field Marketing'],
    ['SMS_CAMPAIGN', 'SMS Campaign'],
    ['EMAIL_CAMPAIGN', 'Email Campaign'],
  ]),

  ...rows('CALL_TYPE', [
    ['INBOUND_QUERY', 'Inbound Query'],
    ['OUTBOUND_FOLLOW_UP', 'Outbound Follow-up'],
    ['SERVICE_BOOKING', 'Service Booking'],
    ['COMPLAINT', 'Complaint'],
    ['SALES_ENQUIRY', 'Sales Enquiry'],
    ['TECHNICAL_SUPPORT', 'Technical Support'],
    ['GENERAL_ENQUIRY', 'General Enquiry'],
    ['FEEDBACK_CALL', 'Feedback Call'],
    ['HAPPY_CALL', 'Happy Call'],
    ['REMINDER_CALL', 'Reminder Call'],
  ]),

  ...rows('APPOINTMENT_SLOT', [
    ['SLOT_08_10', '08:00 AM - 10:00 AM', { startTime: '08:00', endTime: '10:00' }],
    ['SLOT_10_12', '10:00 AM - 12:00 PM', { startTime: '10:00', endTime: '12:00' }],
    ['SLOT_12_14', '12:00 PM - 02:00 PM', { startTime: '12:00', endTime: '14:00' }],
    ['SLOT_14_16', '02:00 PM - 04:00 PM', { startTime: '14:00', endTime: '16:00' }],
    ['SLOT_16_18', '04:00 PM - 06:00 PM', { startTime: '16:00', endTime: '18:00' }],
    ['SLOT_18_20', '06:00 PM - 08:00 PM', { startTime: '18:00', endTime: '20:00' }],
  ]),

  ...rows('PAYMENT_METHOD', [
    ['CASH', 'Cash'],
    ['UPI', 'UPI'],
    ['CARD', 'Credit / Debit Card'],
    ['BANK_TRANSFER', 'Bank Transfer (NEFT/RTGS)'],
    ['GATEWAY', 'Payment Gateway Link'],
    ['CHEQUE', 'Cheque'],
    ['CREDIT', 'Credit (Bill Later)'],
  ]),
  ...rows('CUSTOMER_TYPE', [
    ['RESIDENTIAL', 'Residential'],
    ['COMMERCIAL', 'Commercial'],
  ]),
];
